# 서블릿 설정
spring.main.web-application-type=servlet

# 톰캣 port 번호 
server.port=8099

### 데이터베이스 연동 ###
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=1234

### ViewResolver  Setting (사용하기) ####
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

######## Logging  Setting  ########
logging.level.org.springframework.web=debug
logging.level.org.springframework.security=debug

### src/main/resources에 mapper폴더 내부의 모든폴더(**) 의 모든 xml맵퍼(*.xml) 파일을 맵핑한다
mybatis.mapper-locations=classpath:mapper/**/*.xml

###   자료실 파일 사이즈 설정 ####
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
